version: "3.9"

# Worker template
x-worker-base: &worker-base
  build:
    context: ./backend
    dockerfile: worker/Dockerfile
  restart: unless-stopped
  networks:
    - app-net

services:

  # Backend Orchestrator to disperse tasks to workers and collect results
  orchestrator:
    build:
      context: ./backend
      dockerfile: orchestrator/Dockerfile
    ports:
      - "8000:8000"
    environment:
      WORKER_URLS: ""
    restart: unless-stopped
    networks:
      - app-net

  # Worker containers , each with unique worker id
  worker1:
    <<: *worker-base
    environment:
      WORKER_ID: worker1
      ORCHESTRATOR_URL: http://orchestrator:8000
      WORKER_PUBLIC_URL: http://worker1:8001
      COMPUTER_NAME: local-docker-host

  worker2:
    <<: *worker-base
    environment:
      WORKER_ID: worker2
      ORCHESTRATOR_URL: http://orchestrator:8000
      WORKER_PUBLIC_URL: http://worker2:8001
      COMPUTER_NAME: local-docker-host

  worker3:
    <<: *worker-base
    environment:
      WORKER_ID: worker3
      ORCHESTRATOR_URL: http://orchestrator:8000
      WORKER_PUBLIC_URL: http://worker3:8001
      COMPUTER_NAME: local-docker-host

  worker4:
    <<: *worker-base
    environment:
      WORKER_ID: worker4
      ORCHESTRATOR_URL: http://orchestrator:8000
      WORKER_PUBLIC_URL: http://worker4:8001
      COMPUTER_NAME: local-docker-host

  worker5:
    <<: *worker-base
    environment:
      WORKER_ID: worker5
      ORCHESTRATOR_URL: http://orchestrator:8000
      WORKER_PUBLIC_URL: http://worker5:8001
      COMPUTER_NAME: local-docker-host

  worker6:
    <<: *worker-base
    environment:
      WORKER_ID: worker6
      ORCHESTRATOR_URL: http://orchestrator:8000
      WORKER_PUBLIC_URL: http://worker6:8001
      COMPUTER_NAME: local-docker-host

  worker7:
    <<: *worker-base
    environment:
      WORKER_ID: worker7
      ORCHESTRATOR_URL: http://orchestrator:8000
      WORKER_PUBLIC_URL: http://worker7:8001
      COMPUTER_NAME: local-docker-host

  worker8:
    <<: *worker-base
    environment:
      WORKER_ID: worker8
      ORCHESTRATOR_URL: http://orchestrator:8000
      WORKER_PUBLIC_URL: http://worker8:8001
      COMPUTER_NAME: local-docker-host

  # React frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - orchestrator
    restart: unless-stopped
    networks:
      - app-net

networks:
  app-net:
    driver: bridge
